parameters:

    ecentria.api.domain_message.class:             Ecentria\Libraries\EcentriaAPIEventsBundle\Services\MessageDispatcher
    ecentria.api.domain_message_consumer.class:    Ecentria\Libraries\EcentriaAPIEventsBundle\Consumer\MessageConsumer

services:
    ecentria.api.domain_message.manager:
        class: "%ecentria.api.domain_message.class%"
        arguments:
            - '@event_dispatcher'

    ecentria.api.domain_message_consumer.service:
        class: "%ecentria.api.domain_message_consumer.class%"
        arguments:
            - '@ecentria.api.domain_message.manager'
